name: Build and Deploy Chatbot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t chatbot-app .

    - name: Run tests (optional)
      run: echo "Add your tests here!"

    - name: Push to DockerHub (optional)
      run: echo "You can add DockerHub deployment here"

    - name: Deploy (optional)
      run: echo "You can add your deployment command here"
